default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: BorderBOT-backend_development

test:
  <<: *default
  database: BorderBOT-backend_test

production:
  <<: *default
  database: BorderBOT-backend_production
  username: BorderBOT-backend
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['BORDERBOT-BACKEND_DATABASE_PASSWORD'] %>
